environment:
  smoketest: "node_modules/zeromq/examples/smoketest.js"
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "7"
      electron_run_as_node: "1"
      electron: "1.4.10"
    - nodejs_version: "7"
      electron_run_as_node: "1"
      electron: "1.3.0"
    - nodejs_version: "7"
      electron_run_as_node: "1"
      electron: "1.2.0"
    - nodejs_version: "7"
      electron_run_as_node: "1"
      electron: "1.0.0"

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - IF DEFINED ELECTRON (npm install electron-prebuilt@%ELECTRON%)
  - IF DEFINED ELECTRON (npm install zeromq --runtime=electron --target=%ELECTRON%) ELSE (npm install zeromq)

test_script:
  - IF DEFINED ELECTRON (node_modules\.bin\electron %SMOKETEST%) ELSE (node %SMOKETEST%)

build: off
